name: Create and Merge PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq curl

      - name: Set up Git
        run: |
          git config --global user.email "ranyseleem@gmail.com"
          git config --global user.name "rraneemm"

      - name: Create a PR on the gold repo
        env:
          GITHUB_APP_ID: ${{ secrets.APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          REPO_NAME: gold
          BRANCH_NAME: update-branch
          PR_TITLE: "Automated PR from common-workflows"
          PR_BODY: "This PR was created automatically by GitHub Actions."
        run: |
          # Get a JWT token
          JWT=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"iat":'$(date +%s)',"exp":'$(($(date +%s) + 600))',"iss":"'$GITHUB_APP_ID'"}' \
            https://api.github.com/app/installations/$APP_INSTALLATION_ID/access_tokens \
            -H "Authorization: Bearer $(echo $APP_PRIVATE_KEY | tr -d '\n')" | jq -r .token)

          # Create a new branch and commit changes
          git checkout -b $BRANCH_NAME
          echo "Some changes" > newfile.txt
          git add newfile.txt
          git commit -m "Add new file"

          # Push the branch
          git push https://github.com/Hashemjr/common-workflows.git $BRANCH_NAME

          # Create a PR
          PR_NUMBER=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title":"'$PR_TITLE'","body":"'$PR_BODY'","head":"'$BRANCH_NAME'","base":"main"}' \
            https://api.github.com/repos/$REPO_NAME/pulls | jq -r .number)

          # Merge the PR
          curl -s -X PUT \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method":"merge"}' \
            https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/merge
