name: Create PR

on: push

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from common-workflows
      uses: actions/checkout@v3  

    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:
        application_id: ${{ vars.APP_ID }}
        application_private_key: ${{ secrets.APP_KEY }}    

    - name: Checkout gold repository
      uses: actions/checkout@v3
      with:
        repository: rraneemm/gold
        token: ${{ steps.get_workflow_token.outputs.token }}
        ref: main  

    - name: Generate random number
      id: random
      run: echo "value=$RANDOM" >> $GITHUB_ENV 

    - name: Create file with random number
      run: echo "${{ env.value }}" > random_number${{ env.value }}.txt  
      
    - name: Commit and push new file
      run: |
        git config user.name "rraneemm"
        git config user.email "ranyseleem@gmail.com"
        git checkout -b post-${{ env.value }} 
        git add random_number${{ env.value }}.txt
        git commit -m "New post with random number"
        git push origin post-${{ env.value }}

    - name: Create pull request
      run: gh pr create -B main -H post-${{ env.value }} --title 'Merge branch with random number file' --body 'Created by GitHub action'
      env:
        GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
	
